### ISSUE TITLE
A way to skip scanning the Alliance Missions and focus only on personal.

### ISSUE THREAD

**Issue by Paixtaras** [NatesHonor/MissionchiefBot#5]
Sometimes if you are in a big Alliance they got more than 400 missions.
This will take long time to scan all of them and interact with them and it will take also long time till it reach in personal missions

**Comment by NatesHonor** [comment]
I am working on the personal-only mission mode now. I am adding a configuration switch so the collector can fetch only personal missions or include alliance missions explicitly, while preserving the existing shared marker and dispatch flow.

**Comment by NatesHonor** [comment]
I have completed the personal-only mission collection mode in [671b1a5](https://github.com/NatesHonor/MissionchiefBot-X/commit/671b1a5beabdda7db7a459c10e75552fff276cae), which GitHub has recorded as a commit that references this issue.

Mission collection now always reads the personal mission feed and includes the alliance feed by default for backward compatibility. Set `include_alliance_missions = false` under `[missions]`, or set `MISSIONCHIEF_INCLUDE_ALLIANCE_MISSIONS=false`, to collect and dispatch only personal missions. The setting is covered by the automated test suite and is targeted for MissionchiefBotX v3.1.0.

**Comment by NatesHonor** [comment]
This issue was updated in commit [671b1a5](https://github.com/NatesHonor/MissionchiefBot-X/commit/671b1a5beabdda7db7a459c10e75552fff276cae).
The fix will be included in MissionchiefBotX v3.1.0.
